# Generated by Django 6.0.1 on 2026-03-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynotification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('post', 'New Post'), ('file', 'New File Uploaded'), ('accept', 'Request Accepted'), ('request', 'Join Request'), ('decline', 'Request Declined'), ('invite', 'Invite to Group'), ('create', 'Group Proposal'), ('approve', 'Group Approved'), ('deny', 'Group Denied'), ('delete', 'Group Deleted'), ('post-create', 'Post Proposal'), ('approve', 'Post Approved'), ('deny', 'Post Denied'), ('register', 'Registered User')], max_length=20),
        ),
    ]
