# Generated by Django 6.0.1 on 2026-02-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroupmatch',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
