# Generated by Django 4.2 on 2025-12-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='university',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='university',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(choices=[('SE', 'Software Engineering'), ('KE', 'Knowledge Engineering'), ('HPC', 'High Performance Computing')], max_length=50),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
