# Generated by Django 6.0.1 on 2026-02-14 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coursegroupmatch_is_read_groupinvitation_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='last_chat_view',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='last_feed_view',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
