# Generated by Django 6.0.1 on 2026-03-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activitynotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
