# Generated by Django 6.0.1 on 2026-02-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitynotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynotification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('post', 'New Post'), ('accept', 'Accepted Invite')], max_length=10),
        ),
    ]
