# Generated by Django 4.2 on 2025-12-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_alter_freetimematch_student1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(choices=[('1', 'Software Engineering'), ('2', 'Knowledge Engineering'), ('3', 'High Performance Computing'), ('4', 'Cyber Security & Forensics'), ('5', 'Business Information Systems (BIS)'), ('6', 'Embedded Systems'), ('7', 'Computer Communication and Networks')], max_length=50),
        ),
    ]
