# Generated by Django 4.2 on 2025-12-31 15:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_studentprofile_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroupMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('group_created', 'Group Created')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('agenda', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='slot_type',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_study_days',
            field=models.CharField(default='Mon,Tue,Wed,Thu,Fri', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_study_end',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_study_start',
            field=models.TimeField(default='16:00'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='weekend_study',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_type',
            field=models.CharField(choices=[('major', 'Major-Based'), ('course', 'Course-Based'), ('general', 'General Study')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='max_members',
            field=models.IntegerField(default=200),
        ),
        migrations.DeleteModel(
            name='FreeTimeMatch',
        ),
        migrations.AddField(
            model_name='studysession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.studygroup'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.studysession'),
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='coursegroupmatch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AddField(
            model_name='coursegroupmatch',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_matches', to='core.studentprofile'),
        ),
        migrations.AddField(
            model_name='coursegroupmatch',
            name='target_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to='core.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionattendance',
            unique_together={('session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='coursegroupmatch',
            unique_together={('course', 'initiator', 'target_student')},
        ),
    ]
