# Generated by Django 6.0.1 on 2026-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_activitynotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('programming', 'Programming & Tech'), ('language', 'Foreign Languages'), ('hobby', 'Hobbies & Vibes')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='core.interest'),
        ),
    ]
