# Generated by Django 6.0.1 on 2026-02-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interest_studentprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='core.interest'),
        ),
    ]
