# Generated by Django 6.0 on 2026-02-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_interest_studentprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interest'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='group_type',
            field=models.CharField(choices=[('major', 'Major-Based'), ('course', 'Course-Based'), ('interest', 'Interest-Based'), ('general', 'General Study')], max_length=20),
        ),
    ]
