# Generated by Django 4.2 on 2026-01-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_coursegroupmatch_sessionattendance_studysession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableslot',
            name='slot_type',
            field=models.CharField(choices=[('class', 'Class'), ('self_study', 'Self Study'), ('break', 'Break'), ('activity', 'Activity'), ('free', 'Free Time')], default='free', max_length=20),
        ),
    ]
