# Generated by Django 4.2 on 2026-01-12 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timetableslot_slot_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='preferred_day',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='preferred_end_time',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='preferred_start_time',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='study_day',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
