# Generated by Django 6.0.1 on 2026-02-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_groupjoinrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynotification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('post', 'New Post'), ('accept', 'Accepted Invite'), ('request', 'Group Request'), ('deny', 'Request Deny')], max_length=10),
        ),
    ]
