# Generated by Django 4.2 on 2026-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_studygroup_preferred_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', 'Semester 1'), ('2', 'Semester 2'), ('3', 'Semester 3'), ('4', 'Semester 4'), ('5', 'Semester 5'), ('6', 'Semester 6'), ('7', 'Semester 7'), ('8', 'Semester 8'), ('9', 'Semester 9'), ('10', 'Semester 10')], max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'semester')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
    ]
