# Generated by Django 6.0.1 on 2026-02-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_activitynotification_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitynotification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('post', 'New Post'), ('file', 'New File Uploaded'), ('accept', 'Request Accepted'), ('request', 'Join Request'), ('decline', 'Request Declined'), ('create', 'Group Proposal'), ('approve', 'Group Approved'), ('deny', 'Group Denied'), ('delete', 'Group Deleted'), ('register', 'Registered User')], max_length=10),
        ),
    ]
