# Generated by Django 6.0.1 on 2026-02-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_activitynotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_groups', to='core.interest'),
        ),
    ]
