# Generated by Django 6.0.1 on 2026-02-27 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studygroup_status_alter_studygroup_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
