# Generated by Django 6.0.1 on 2026-03-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_grouppost_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_comments/'),
        ),
    ]
