# Generated by Django 6.0.1 on 2026-03-03 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_grouppost_is_approved_postcomment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='GroupPost',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='activitynotification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('post', 'New Post'), ('file', 'New File Uploaded'), ('accept', 'Request Accepted'), ('request', 'Join Request'), ('decline', 'Request Declined'), ('create', 'Group Proposal'), ('approve', 'Group Approved'), ('deny', 'Group Denied'), ('delete', 'Group Deleted'), ('post-create', 'Post Proposal'), ('approve', 'Post Approved'), ('deny', 'Post Denied'), ('register', 'Registered User')], max_length=20),
        ),
    ]
