# Generated by Django 6.0.1 on 2026-03-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_postcomment_comment_rename_grouppost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='pending', max_length=15),
        ),
    ]
