# Generated by Django 6.0.1 on 2026-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_groupmembership_is_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvitation',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
