# Generated by Django 6.0 on 2026-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_grouppost_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
