# Generated by Django 6.0 on 2026-01-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_grouppost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
