# Generated by Django 6.0.1 on 2026-02-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('image', 'Image'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet'), ('archive', 'Archive'), ('other', 'Other')], max_length=50),
        ),
    ]
