# Generated by Django 6.0.1 on 2026-02-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_sharedfile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
