# Generated by Django 6.0.1 on 2026-03-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='likes',
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('image', 'Image'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet'), ('archive', 'Archive'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
