# Generated by Django 6.0.1 on 2026-04-11 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='is_chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='is_video_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
