# Generated by Django 6.0.1 on 2026-04-25 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('groups', '0002_studygroup_is_chat_enabled_and_more'),
        ('users', '0002_alter_studentprofile_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='users.major'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='unique_group_membership'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='groups.category'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='groups', to='groups.tag'),
        ),
    ]
