# Generated by Django 6.0.1 on 2026-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_category_tag_alter_groupmembership_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='group_type',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=10),
        ),
    ]
