# Generated by Django 6.0.1 on 2026-04-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_studygroup_group_type_studygroup_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='major',
        ),
    ]
